/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEquipamentosRouteImport } from './routes/_authenticated/equipamentos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCautelasRouteImport } from './routes/_authenticated/cautelas'
import { Route as AuthenticatedCautelasNovaRouteImport } from './routes/_authenticated/cautelas.nova'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEquipamentosRoute =
  AuthenticatedEquipamentosRouteImport.update({
    id: '/equipamentos',
    path: '/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCautelasRoute = AuthenticatedCautelasRouteImport.update({
  id: '/cautelas',
  path: '/cautelas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCautelasNovaRoute =
  AuthenticatedCautelasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedCautelasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cautelas': typeof AuthenticatedCautelasRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/cautelas/nova': typeof AuthenticatedCautelasNovaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/cautelas': typeof AuthenticatedCautelasRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/cautelas/nova': typeof AuthenticatedCautelasNovaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/cautelas': typeof AuthenticatedCautelasRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/equipamentos': typeof AuthenticatedEquipamentosRoute
  '/_authenticated/cautelas/nova': typeof AuthenticatedCautelasNovaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/cautelas'
    | '/dashboard'
    | '/equipamentos'
    | '/cautelas/nova'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/cautelas'
    | '/dashboard'
    | '/equipamentos'
    | '/cautelas/nova'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/cautelas'
    | '/_authenticated/dashboard'
    | '/_authenticated/equipamentos'
    | '/_authenticated/cautelas/nova'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/equipamentos': {
      id: '/_authenticated/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof AuthenticatedEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cautelas': {
      id: '/_authenticated/cautelas'
      path: '/cautelas'
      fullPath: '/cautelas'
      preLoaderRoute: typeof AuthenticatedCautelasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cautelas/nova': {
      id: '/_authenticated/cautelas/nova'
      path: '/nova'
      fullPath: '/cautelas/nova'
      preLoaderRoute: typeof AuthenticatedCautelasNovaRouteImport
      parentRoute: typeof AuthenticatedCautelasRoute
    }
  }
}

interface AuthenticatedCautelasRouteChildren {
  AuthenticatedCautelasNovaRoute: typeof AuthenticatedCautelasNovaRoute
}

const AuthenticatedCautelasRouteChildren: AuthenticatedCautelasRouteChildren = {
  AuthenticatedCautelasNovaRoute: AuthenticatedCautelasNovaRoute,
}

const AuthenticatedCautelasRouteWithChildren =
  AuthenticatedCautelasRoute._addFileChildren(
    AuthenticatedCautelasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCautelasRoute: typeof AuthenticatedCautelasRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEquipamentosRoute: typeof AuthenticatedEquipamentosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCautelasRoute: AuthenticatedCautelasRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEquipamentosRoute: AuthenticatedEquipamentosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
